/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    ProjectsList: typeof import('./components/Projects/ProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
